kind: ConfigMap
apiVersion: v1
metadata:
  name: cassandra-config
data:
  cassandra.dc: "DC1"
  cassandra.rack: "RACK1"
  cassandra.cluster_name: "OAI_HSS"
  cassandra.endpoint_snitch: "GossipingPropertyFileSnitch"
