apiVersion: v1
kind: Service
metadata:
  labels:
    app: oai-enb
  name: oai-enb
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: oai-enb
    port: 22100
    protocol: TCP
    targetPort: 22100
  - name: s1u
    port: 2152
    protocol: UDP
    targetPort: 2152
  - name: s1c
    port: 36412
    protocol: UDP
    targetPort: 36412
  - name: x2c
    port: 36422
    protocol: UDP
    targetPort: 36422
  - name: if5-ori
    port: 50000
    protocol: UDP
    targetPort: 50000
  - name: if5-ecpri
    port: 50001
    protocol: UDP
    targetPort: 50001
  selector:
    app: oai-enb
