apiVersion: v1
kind: Service
metadata:
  labels:
    app: oai-spgwc
  name: oai-spgwc
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: oai-spgwc
    port: 8805
    protocol: TCP
    targetPort: 8805
  - name: s11
    port: 2123
    protocol: UDP
    targetPort: 2123
  selector:
    app: oai-spgwc
