apiVersion: v1
kind: ConfigMap
metadata:
  name: spgwu-config
data:
  sgw_s1u_if: net2
  sgw_sx_if: net1
  pgw_sgi_if: net3
  net_ue_ip: 192.168.20.0/24
  pgwc_sx_ip: 192.168.2.100
  pgwu_sgi_gw : 192.168.3.101
