apiVersion: v1
kind: Service
metadata:
  labels:
    app: oai-spgwu
  name: oai-spgwu
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: oai-spgwu
    port: 8805
    protocol: UDP
    targetPort: 8805
  - name: s11
    port: 2152
    protocol: UDP
    targetPort: 2152
  selector:
    app: oai-spgwu
