apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app: mariadb
  name: mariadb-secret
data:
  database-name: aHNz
  database-password: dXNlcnBhc3M=
  database-root-password: cm9vdHBhc3M=
  database-user: dXNlcg==
