apiVersion: v1
kind: Service
metadata:
  labels:
    app: oai-mme
  name: oai-mme
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: oai-mme
    port: 3870
    protocol: TCP
    targetPort: 3870
  - name: oai-mme-secure
    port: 5870
    protocol: TCP
    targetPort: 5870
  - name: s11
    port: 2123
    protocol: TCP
    targetPort: 2123
  selector:
    app: oai-mme
