resources:
 - 00_mme-sa.yaml
 - 01_mme-rbac.yaml
 - 02_configmap.yaml
 - 03_service.yaml
 - 04_multus.yaml
 - 05_deployment.yaml


namespace: oai

secretGenerator:
- name: mme-tls-secret
  namespace: default
  files:
  - certs/mme.cacert.pem
  - certs/mme.cert.pem
  - certs/mme.key.pem
  type: "Opaque"
generatorOptions:
  disableNameSuffixHash: true
